/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class cFileMappingTelloEduTelemetryServeur {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected cFileMappingTelloEduTelemetryServeur(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cFileMappingTelloEduTelemetryServeur obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNIFileMappingTelloEduTelemetryServeurJNI.delete_cFileMappingTelloEduTelemetryServeur(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public cFileMappingTelloEduTelemetryServeur(boolean _DebugFlag) {
    this(JNIFileMappingTelloEduTelemetryServeurJNI.new_cFileMappingTelloEduTelemetryServeur(_DebugFlag), true);
  }

  public boolean OpenServer(String NameSharedMem) {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_OpenServer(swigCPtr, this, NameSharedMem);
  }

  public void CloseServer() {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_CloseServer(swigCPtr, this);
  }

  public cVirtualTelloEduTelemetry ReadMapFileToVirtualTelloEduTelemetryStruct(cVirtualTelloEduTelemetry Data) {
    long cPtr = JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_ReadMapFileToVirtualTelloEduTelemetryStruct(swigCPtr, this, cVirtualTelloEduTelemetry.getCPtr(Data), Data);
    return (cPtr == 0) ? null : new cVirtualTelloEduTelemetry(cPtr, false);
  }

  public boolean WriteVirtualTelloEduTelemetryStructToMapFile(cVirtualTelloEduTelemetry Data) {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_WriteVirtualTelloEduTelemetryStructToMapFile(swigCPtr, this, cVirtualTelloEduTelemetry.getCPtr(Data), Data);
  }

  public void PrintDebug(String msg, boolean _Return) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_PrintDebug(swigCPtr, this, msg, _Return);
  }

  public void PrintStruct(cVirtualTelloEduTelemetry Data) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_PrintStruct(swigCPtr, this, cVirtualTelloEduTelemetry.getCPtr(Data), Data);
  }

  public cVirtualTelloEduTelemetry getVirtualTelloEduTelemetryPtr() {
    long cPtr = JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryPtr(swigCPtr, this);
    return (cPtr == 0) ? null : new cVirtualTelloEduTelemetry(cPtr, false);
  }

  public boolean getDebugMode() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getDebugMode(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryBatteryValue() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryBatteryValue(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryFlyTime() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryFlyTime(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryTempl() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryTempl(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryTemph() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryTemph(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryToF() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryToF(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryH() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryH(swigCPtr, this);
  }

  public double getVirtualTelloEduTelemetryAgx() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryAgx(swigCPtr, this);
  }

  public double getVirtualTelloEduTelemetryAgy() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryAgy(swigCPtr, this);
  }

  public double getVirtualTelloEduTelemetryAgz() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryAgz(swigCPtr, this);
  }

  public boolean getVirtualTelloEduTelemetryMutexBlocAccess() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryMutexBlocAccess(swigCPtr, this);
  }

  public boolean getVirtualTelloEduTelemetryReadByClient() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryReadByClient(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryPitch() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryPitch(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryRoll() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryRoll(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryYaw() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryYaw(swigCPtr, this);
  }

  public double getVirtualTelloEduTelemetryVgx() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryVgx(swigCPtr, this);
  }

  public double getVirtualTelloEduTelemetryVgy() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryVgy(swigCPtr, this);
  }

  public double getVirtualTelloEduTelemetryVgz() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryVgz(swigCPtr, this);
  }

  public double getVirtualTelloEduTelemetryBaro() {
    return JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_getVirtualTelloEduTelemetryBaro(swigCPtr, this);
  }

  public void setVirtualTelloEduTelemetryPtr(cVirtualTelloEduTelemetry VTStruct) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryPtr(swigCPtr, this, cVirtualTelloEduTelemetry.getCPtr(VTStruct), VTStruct);
  }

  public void setDebugMode(boolean _DebugMode) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setDebugMode(swigCPtr, this, _DebugMode);
  }

  public void setVirtualTelloEduTelemetryBatteryValue(int value) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryBatteryValue(swigCPtr, this, value);
  }

  public void setVirtualTelloEduTelemetryFlyTime(int FlyTime) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryFlyTime(swigCPtr, this, FlyTime);
  }

  public void setVirtualTelloEduTelemetryTempl(int Templ) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryTempl(swigCPtr, this, Templ);
  }

  public void setVirtualTelloEduTelemetryTemph(int Temph) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryTemph(swigCPtr, this, Temph);
  }

  public void setVirtualTelloEduTelemetryToF(int ToF) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryToF(swigCPtr, this, ToF);
  }

  public void setVirtualTelloEduTelemetryH(int H) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryH(swigCPtr, this, H);
  }

  public void setVirtualTelloEduTelemetryAgx(double Agx) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryAgx(swigCPtr, this, Agx);
  }

  public void setVirtualTelloEduTelemetryAgy(double Agy) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryAgy(swigCPtr, this, Agy);
  }

  public void setVirtualTelloEduTelemetryAgz(double Agz) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryAgz(swigCPtr, this, Agz);
  }

  public void setVirtualTelloEduTelemetryMutexBlocAccess(boolean blocaccess) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryMutexBlocAccess(swigCPtr, this, blocaccess);
  }

  public void setVirtualTelloEduTelemetryWriteByServer(boolean etat) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryWriteByServer(swigCPtr, this, etat);
  }

  public void setVirtualTelloEduTelemetryPitch(int Pitch) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryPitch(swigCPtr, this, Pitch);
  }

  public void setVirtualTelloEduTelemetryRoll(int Roll) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryRoll(swigCPtr, this, Roll);
  }

  public void setVirtualTelloEduTelemetryYaw(int Yaw) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryYaw(swigCPtr, this, Yaw);
  }

  public void setVirtualTelloEduTelemetryVgx(double Vgx) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryVgx(swigCPtr, this, Vgx);
  }

  public void setVirtualTelloEduTelemetryVgy(double Vgy) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryVgy(swigCPtr, this, Vgy);
  }

  public void setVirtualTelloEduTelemetryVgz(double Vgz) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryVgz(swigCPtr, this, Vgz);
  }

  public void setVirtualTelloEduTelemetryBaro(double Baro) {
    JNIFileMappingTelloEduTelemetryServeurJNI.cFileMappingTelloEduTelemetryServeur_setVirtualTelloEduTelemetryBaro(swigCPtr, this, Baro);
  }

}
