/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class cFileMappingTelloEduTelemetryClient {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected cFileMappingTelloEduTelemetryClient(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cFileMappingTelloEduTelemetryClient obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNIFileMappingTelloEduTelemetryClientJNI.delete_cFileMappingTelloEduTelemetryClient(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public cFileMappingTelloEduTelemetryClient(boolean _DebugFlag) {
    this(JNIFileMappingTelloEduTelemetryClientJNI.new_cFileMappingTelloEduTelemetryClient(_DebugFlag), true);
  }

  public boolean OpenClient(String NameSharedMem) {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_OpenClient(swigCPtr, this, NameSharedMem);
  }

  public void CloseClient() {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_CloseClient(swigCPtr, this);
  }

  public cVirtualTelloEduTelemetry ReadMapFileToVirtualTelloEduTelemetryStruct(cVirtualTelloEduTelemetry Data) {
    long cPtr = JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_ReadMapFileToVirtualTelloEduTelemetryStruct(swigCPtr, this, cVirtualTelloEduTelemetry.getCPtr(Data), Data);
    return (cPtr == 0) ? null : new cVirtualTelloEduTelemetry(cPtr, false);
  }

  public boolean WriteVirtualTelloEduTelemetryStructToMapFile(cVirtualTelloEduTelemetry Data) {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_WriteVirtualTelloEduTelemetryStructToMapFile(swigCPtr, this, cVirtualTelloEduTelemetry.getCPtr(Data), Data);
  }

  public void PrintDebug(String msg, boolean _Return) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_PrintDebug(swigCPtr, this, msg, _Return);
  }

  public void PrintStruct(cVirtualTelloEduTelemetry Data) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_PrintStruct(swigCPtr, this, cVirtualTelloEduTelemetry.getCPtr(Data), Data);
  }

  public cVirtualTelloEduTelemetry getVirtualTelloEduTelemetryPtr() {
    long cPtr = JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryPtr(swigCPtr, this);
    return (cPtr == 0) ? null : new cVirtualTelloEduTelemetry(cPtr, false);
  }

  public boolean getDebugMode() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getDebugMode(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryBatteryValue() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryBatteryValue(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryFlyTime() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryFlyTime(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryTempl() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryTempl(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryTemph() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryTemph(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryToF() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryToF(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryH() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryH(swigCPtr, this);
  }

  public double getVirtualTelloEduTelemetryAgx() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryAgx(swigCPtr, this);
  }

  public double getVirtualTelloEduTelemetryAgy() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryAgy(swigCPtr, this);
  }

  public double getVirtualTelloEduTelemetryAgz() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryAgz(swigCPtr, this);
  }

  public boolean getVirtualTelloEduTelemetryMutexBlocAccess() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryMutexBlocAccess(swigCPtr, this);
  }

  public boolean getVirtualTelloEduTelemetryWriteByServer() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryWriteByServer(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryPitch() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryPitch(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryRoll() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryRoll(swigCPtr, this);
  }

  public int getVirtualTelloEduTelemetryYaw() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryYaw(swigCPtr, this);
  }

  public double getVirtualTelloEduTelemetryVgx() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryVgx(swigCPtr, this);
  }

  public double getVirtualTelloEduTelemetryVgy() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryVgy(swigCPtr, this);
  }

  public double getVirtualTelloEduTelemetryVgz() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryVgz(swigCPtr, this);
  }

  public double getVirtualTelloEduTelemetryBaro() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryBaro(swigCPtr, this);
  }

  public void setVirtualTelloEduTelemetryPtr(cVirtualTelloEduTelemetry VPStruct) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryPtr(swigCPtr, this, cVirtualTelloEduTelemetry.getCPtr(VPStruct), VPStruct);
  }

  public void setDebugMode(boolean _DebugMode) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setDebugMode(swigCPtr, this, _DebugMode);
  }

  public void setVirtualTelloEduTelemetryBatteryValue(int value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryBatteryValue(swigCPtr, this, value);
  }

  public void setVirtualTelloEduTelemetryFlyTime(int FlyTime) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryFlyTime(swigCPtr, this, FlyTime);
  }

  public void setVirtualTelloEduTelemetryTempl(int Templ) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryTempl(swigCPtr, this, Templ);
  }

  public void setVirtualTelloEduTelemetryTemph(int Temph) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryTemph(swigCPtr, this, Temph);
  }

  public void setVirtualTelloEduTelemetryToF(int ToF) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryToF(swigCPtr, this, ToF);
  }

  public void setVirtualTelloEduTelemetryH(int H) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryH(swigCPtr, this, H);
  }

  public void setVirtualTelloEduTelemetryAgx(double Agx) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryAgx(swigCPtr, this, Agx);
  }

  public void setVirtualTelloEduTelemetryAgy(double Agy) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryAgy(swigCPtr, this, Agy);
  }

  public void setVirtualTelloEduTelemetryAgz(double Agz) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryAgz(swigCPtr, this, Agz);
  }

  public void setVirtualTelloEduTelemetryMutexBlocAccess(boolean blocaccess) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryMutexBlocAccess(swigCPtr, this, blocaccess);
  }

  public void setVirtualTelloEduTelemetryReadByClient(boolean etat) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryReadByClient(swigCPtr, this, etat);
  }

  public void setVirtualTelloEduTelemetryPitch(int Pitch) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryPitch(swigCPtr, this, Pitch);
  }

  public void setVirtualTelloEduTelemetryRoll(int Roll) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryRoll(swigCPtr, this, Roll);
  }

  public void setVirtualTelloEduTelemetryYaw(int Yaw) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryYaw(swigCPtr, this, Yaw);
  }

  public void setVirtualTelloEduTelemetryVgx(double Vgx) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryVgx(swigCPtr, this, Vgx);
  }

  public void setVirtualTelloEduTelemetryVgy(double Vgy) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryVgy(swigCPtr, this, Vgy);
  }

  public void setVirtualTelloEduTelemetryVgz(double Vgz) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryVgz(swigCPtr, this, Vgz);
  }

  public void setVirtualTelloEduTelemetryBaro(double Baro) {
    JNIFileMappingTelloEduTelemetryClientJNI.cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryBaro(swigCPtr, this, Baro);
  }

}
