/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class cVirtualTelloEduTelemetry {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected cVirtualTelloEduTelemetry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cVirtualTelloEduTelemetry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNIFileMappingTelloEduTelemetryClientJNI.delete_cVirtualTelloEduTelemetry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMutexBlocAccess(boolean value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_MutexBlocAccess_set(swigCPtr, this, value);
  }

  public boolean getMutexBlocAccess() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_MutexBlocAccess_get(swigCPtr, this);
  }

  public void setReadByClient(boolean value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_ReadByClient_set(swigCPtr, this, value);
  }

  public boolean getReadByClient() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_ReadByClient_get(swigCPtr, this);
  }

  public void setWritebyServer(boolean value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_WritebyServer_set(swigCPtr, this, value);
  }

  public boolean getWritebyServer() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_WritebyServer_get(swigCPtr, this);
  }

  public void setBatteryValue(int value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_BatteryValue_set(swigCPtr, this, value);
  }

  public int getBatteryValue() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_BatteryValue_get(swigCPtr, this);
  }

  public void setFlyTime(int value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_FlyTime_set(swigCPtr, this, value);
  }

  public int getFlyTime() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_FlyTime_get(swigCPtr, this);
  }

  public void setTempl(int value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Templ_set(swigCPtr, this, value);
  }

  public int getTempl() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Templ_get(swigCPtr, this);
  }

  public void setTemph(int value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Temph_set(swigCPtr, this, value);
  }

  public int getTemph() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Temph_get(swigCPtr, this);
  }

  public void setToF(int value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_ToF_set(swigCPtr, this, value);
  }

  public int getToF() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_ToF_get(swigCPtr, this);
  }

  public void setH(int value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_H_set(swigCPtr, this, value);
  }

  public int getH() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_H_get(swigCPtr, this);
  }

  public void setAgx(double value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Agx_set(swigCPtr, this, value);
  }

  public double getAgx() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Agx_get(swigCPtr, this);
  }

  public void setAgy(double value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Agy_set(swigCPtr, this, value);
  }

  public double getAgy() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Agy_get(swigCPtr, this);
  }

  public void setAgz(double value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Agz_set(swigCPtr, this, value);
  }

  public double getAgz() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Agz_get(swigCPtr, this);
  }

  public void setTelloEduTelemetryDataPtr(SWIGTYPE_p_unsigned_char value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_TelloEduTelemetryDataPtr_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getTelloEduTelemetryDataPtr() {
    long cPtr = JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_TelloEduTelemetryDataPtr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setPitch(int value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Pitch_set(swigCPtr, this, value);
  }

  public int getPitch() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Pitch_get(swigCPtr, this);
  }

  public void setRoll(int value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Roll_set(swigCPtr, this, value);
  }

  public int getRoll() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Roll_get(swigCPtr, this);
  }

  public void setYaw(int value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Yaw_set(swigCPtr, this, value);
  }

  public int getYaw() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Yaw_get(swigCPtr, this);
  }

  public void setVgx(double value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Vgx_set(swigCPtr, this, value);
  }

  public double getVgx() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Vgx_get(swigCPtr, this);
  }

  public void setVgy(double value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Vgy_set(swigCPtr, this, value);
  }

  public double getVgy() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Vgy_get(swigCPtr, this);
  }

  public void setVgz(double value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Vgz_set(swigCPtr, this, value);
  }

  public double getVgz() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Vgz_get(swigCPtr, this);
  }

  public void setBaro(double value) {
    JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Baro_set(swigCPtr, this, value);
  }

  public double getBaro() {
    return JNIFileMappingTelloEduTelemetryClientJNI.cVirtualTelloEduTelemetry_Baro_get(swigCPtr, this);
  }

  public cVirtualTelloEduTelemetry() {
    this(JNIFileMappingTelloEduTelemetryClientJNI.new_cVirtualTelloEduTelemetry(), true);
  }

}

