/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class cVirtualManettes {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected cVirtualManettes(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cVirtualManettes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNIFileMappingManettesClientJNI.delete_cVirtualManettes(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMutexBlocAccess(boolean value) {
    JNIFileMappingManettesClientJNI.cVirtualManettes_MutexBlocAccess_set(swigCPtr, this, value);
  }

  public boolean getMutexBlocAccess() {
    return JNIFileMappingManettesClientJNI.cVirtualManettes_MutexBlocAccess_get(swigCPtr, this);
  }

  public void setManettesDataPtr(SWIGTYPE_p_unsigned_char value) {
    JNIFileMappingManettesClientJNI.cVirtualManettes_ManettesDataPtr_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getManettesDataPtr() {
    long cPtr = JNIFileMappingManettesClientJNI.cVirtualManettes_ManettesDataPtr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setAxeX_Gauche(double value) {
    JNIFileMappingManettesClientJNI.cVirtualManettes_AxeX_Gauche_set(swigCPtr, this, value);
  }

  public double getAxeX_Gauche() {
    return JNIFileMappingManettesClientJNI.cVirtualManettes_AxeX_Gauche_get(swigCPtr, this);
  }

  public void setAxeY_Gauche(double value) {
    JNIFileMappingManettesClientJNI.cVirtualManettes_AxeY_Gauche_set(swigCPtr, this, value);
  }

  public double getAxeY_Gauche() {
    return JNIFileMappingManettesClientJNI.cVirtualManettes_AxeY_Gauche_get(swigCPtr, this);
  }

  public void setAxeX_Droite(double value) {
    JNIFileMappingManettesClientJNI.cVirtualManettes_AxeX_Droite_set(swigCPtr, this, value);
  }

  public double getAxeX_Droite() {
    return JNIFileMappingManettesClientJNI.cVirtualManettes_AxeX_Droite_get(swigCPtr, this);
  }

  public void setAxeY_Droite(double value) {
    JNIFileMappingManettesClientJNI.cVirtualManettes_AxeY_Droite_set(swigCPtr, this, value);
  }

  public double getAxeY_Droite() {
    return JNIFileMappingManettesClientJNI.cVirtualManettes_AxeY_Droite_get(swigCPtr, this);
  }

  public cVirtualManettes() {
    this(JNIFileMappingManettesClientJNI.new_cVirtualManettes(), true);
  }

}
