/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class cVirtualRobotHaptiqueDrone {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected cVirtualRobotHaptiqueDrone(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cVirtualRobotHaptiqueDrone obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(cVirtualRobotHaptiqueDrone obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNIFileMappingRobotHaptiqueDroneClientJNI.delete_cVirtualRobotHaptiqueDrone(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMutexBlocAccess(boolean value) {
    JNIFileMappingRobotHaptiqueDroneClientJNI.cVirtualRobotHaptiqueDrone_MutexBlocAccess_set(swigCPtr, this, value);
  }

  public boolean getMutexBlocAccess() {
    return JNIFileMappingRobotHaptiqueDroneClientJNI.cVirtualRobotHaptiqueDrone_MutexBlocAccess_get(swigCPtr, this);
  }

  public void setUserPresence(boolean value) {
    JNIFileMappingRobotHaptiqueDroneClientJNI.cVirtualRobotHaptiqueDrone_UserPresence_set(swigCPtr, this, value);
  }

  public boolean getUserPresence() {
    return JNIFileMappingRobotHaptiqueDroneClientJNI.cVirtualRobotHaptiqueDrone_UserPresence_get(swigCPtr, this);
  }

  public void setRobotHaptiqueDroneDataPtr(SWIGTYPE_p_unsigned_char value) {
    JNIFileMappingRobotHaptiqueDroneClientJNI.cVirtualRobotHaptiqueDrone_RobotHaptiqueDroneDataPtr_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getRobotHaptiqueDroneDataPtr() {
    long cPtr = JNIFileMappingRobotHaptiqueDroneClientJNI.cVirtualRobotHaptiqueDrone_RobotHaptiqueDroneDataPtr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setAxeX(int value) {
    JNIFileMappingRobotHaptiqueDroneClientJNI.cVirtualRobotHaptiqueDrone_AxeX_set(swigCPtr, this, value);
  }

  public int getAxeX() {
    return JNIFileMappingRobotHaptiqueDroneClientJNI.cVirtualRobotHaptiqueDrone_AxeX_get(swigCPtr, this);
  }

  public void setAxeY(int value) {
    JNIFileMappingRobotHaptiqueDroneClientJNI.cVirtualRobotHaptiqueDrone_AxeY_set(swigCPtr, this, value);
  }

  public int getAxeY() {
    return JNIFileMappingRobotHaptiqueDroneClientJNI.cVirtualRobotHaptiqueDrone_AxeY_get(swigCPtr, this);
  }

  public void setAxeZ(int value) {
    JNIFileMappingRobotHaptiqueDroneClientJNI.cVirtualRobotHaptiqueDrone_AxeZ_set(swigCPtr, this, value);
  }

  public int getAxeZ() {
    return JNIFileMappingRobotHaptiqueDroneClientJNI.cVirtualRobotHaptiqueDrone_AxeZ_get(swigCPtr, this);
  }

  public cVirtualRobotHaptiqueDrone() {
    this(JNIFileMappingRobotHaptiqueDroneClientJNI.new_cVirtualRobotHaptiqueDrone(), true);
  }

}
