/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class JNIFileMappingTelloEduTelemetryClientJNI {
  public final static native void cVirtualTelloEduTelemetry_MutexBlocAccess_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, boolean jarg2);
  public final static native boolean cVirtualTelloEduTelemetry_MutexBlocAccess_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_ReadByClient_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, boolean jarg2);
  public final static native boolean cVirtualTelloEduTelemetry_ReadByClient_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_WritebyServer_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, boolean jarg2);
  public final static native boolean cVirtualTelloEduTelemetry_WritebyServer_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_BatteryValue_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_BatteryValue_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_FlyTime_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_FlyTime_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Templ_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_Templ_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Temph_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_Temph_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_ToF_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_ToF_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_H_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_H_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Agx_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, double jarg2);
  public final static native double cVirtualTelloEduTelemetry_Agx_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Agy_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, double jarg2);
  public final static native double cVirtualTelloEduTelemetry_Agy_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Agz_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, double jarg2);
  public final static native double cVirtualTelloEduTelemetry_Agz_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_TelloEduTelemetryDataPtr_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, long jarg2);
  public final static native long cVirtualTelloEduTelemetry_TelloEduTelemetryDataPtr_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Pitch_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_Pitch_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Roll_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_Roll_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Yaw_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_Yaw_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Vgx_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, double jarg2);
  public final static native double cVirtualTelloEduTelemetry_Vgx_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Vgy_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, double jarg2);
  public final static native double cVirtualTelloEduTelemetry_Vgy_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Vgz_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, double jarg2);
  public final static native double cVirtualTelloEduTelemetry_Vgz_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Baro_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, double jarg2);
  public final static native double cVirtualTelloEduTelemetry_Baro_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native long new_cVirtualTelloEduTelemetry();
  public final static native void delete_cVirtualTelloEduTelemetry(long jarg1);
  public final static native long new_cFileMappingTelloEduTelemetryClient(boolean jarg1);
  public final static native void delete_cFileMappingTelloEduTelemetryClient(long jarg1);
  public final static native boolean cFileMappingTelloEduTelemetryClient_OpenClient(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, String jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_CloseClient(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native long cFileMappingTelloEduTelemetryClient_ReadMapFileToVirtualTelloEduTelemetryStruct(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, long jarg2, cVirtualTelloEduTelemetry jarg2_);
  public final static native boolean cFileMappingTelloEduTelemetryClient_WriteVirtualTelloEduTelemetryStructToMapFile(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, long jarg2, cVirtualTelloEduTelemetry jarg2_);
  public final static native void cFileMappingTelloEduTelemetryClient_PrintDebug(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, String jarg2, boolean jarg3);
  public final static native void cFileMappingTelloEduTelemetryClient_PrintStruct(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, long jarg2, cVirtualTelloEduTelemetry jarg2_);
  public final static native long cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryPtr(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native boolean cFileMappingTelloEduTelemetryClient_getDebugMode(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native int cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryBatteryValue(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native int cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryFlyTime(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native int cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryTempl(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native int cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryTemph(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native int cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryToF(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native int cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryH(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native double cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryAgx(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native double cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryAgy(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native double cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryAgz(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native boolean cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryMutexBlocAccess(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native boolean cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryWriteByServer(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native int cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryPitch(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native int cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryRoll(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native int cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryYaw(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native double cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryVgx(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native double cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryVgy(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native double cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryVgz(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native double cFileMappingTelloEduTelemetryClient_getVirtualTelloEduTelemetryBaro(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryPtr(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, long jarg2, cVirtualTelloEduTelemetry jarg2_);
  public final static native void cFileMappingTelloEduTelemetryClient_setDebugMode(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, boolean jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryBatteryValue(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, int jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryFlyTime(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, int jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryTempl(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, int jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryTemph(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, int jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryToF(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, int jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryH(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, int jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryAgx(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, double jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryAgy(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, double jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryAgz(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, double jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryMutexBlocAccess(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, boolean jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryReadByClient(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, boolean jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryPitch(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, int jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryRoll(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, int jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryYaw(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, int jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryVgx(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, double jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryVgy(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, double jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryVgz(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, double jarg2);
  public final static native void cFileMappingTelloEduTelemetryClient_setVirtualTelloEduTelemetryBaro(long jarg1, cFileMappingTelloEduTelemetryClient jarg1_, double jarg2);
}
