/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class JNIFileMappingRobotHaptiqueDroneClientJNI {
  public final static native void cVirtualRobotHaptiqueDrone_MutexBlocAccess_set(long jarg1, cVirtualRobotHaptiqueDrone jarg1_, boolean jarg2);
  public final static native boolean cVirtualRobotHaptiqueDrone_MutexBlocAccess_get(long jarg1, cVirtualRobotHaptiqueDrone jarg1_);
  public final static native void cVirtualRobotHaptiqueDrone_UserPresence_set(long jarg1, cVirtualRobotHaptiqueDrone jarg1_, boolean jarg2);
  public final static native boolean cVirtualRobotHaptiqueDrone_UserPresence_get(long jarg1, cVirtualRobotHaptiqueDrone jarg1_);
  public final static native void cVirtualRobotHaptiqueDrone_RobotHaptiqueDroneDataPtr_set(long jarg1, cVirtualRobotHaptiqueDrone jarg1_, long jarg2);
  public final static native long cVirtualRobotHaptiqueDrone_RobotHaptiqueDroneDataPtr_get(long jarg1, cVirtualRobotHaptiqueDrone jarg1_);
  public final static native void cVirtualRobotHaptiqueDrone_AxeX_set(long jarg1, cVirtualRobotHaptiqueDrone jarg1_, int jarg2);
  public final static native int cVirtualRobotHaptiqueDrone_AxeX_get(long jarg1, cVirtualRobotHaptiqueDrone jarg1_);
  public final static native void cVirtualRobotHaptiqueDrone_AxeY_set(long jarg1, cVirtualRobotHaptiqueDrone jarg1_, int jarg2);
  public final static native int cVirtualRobotHaptiqueDrone_AxeY_get(long jarg1, cVirtualRobotHaptiqueDrone jarg1_);
  public final static native void cVirtualRobotHaptiqueDrone_AxeZ_set(long jarg1, cVirtualRobotHaptiqueDrone jarg1_, int jarg2);
  public final static native int cVirtualRobotHaptiqueDrone_AxeZ_get(long jarg1, cVirtualRobotHaptiqueDrone jarg1_);
  public final static native long new_cVirtualRobotHaptiqueDrone();
  public final static native void delete_cVirtualRobotHaptiqueDrone(long jarg1);
  public final static native long new_cFileMappingRobotHaptiqueDroneClient(boolean jarg1);
  public final static native void delete_cFileMappingRobotHaptiqueDroneClient(long jarg1);
  public final static native boolean cFileMappingRobotHaptiqueDroneClient_OpenClient(long jarg1, cFileMappingRobotHaptiqueDroneClient jarg1_, String jarg2);
  public final static native void cFileMappingRobotHaptiqueDroneClient_CloseClient(long jarg1, cFileMappingRobotHaptiqueDroneClient jarg1_);
  public final static native long cFileMappingRobotHaptiqueDroneClient_ReadMapFileToVirtualRobotHaptiqueDroneStruct(long jarg1, cFileMappingRobotHaptiqueDroneClient jarg1_, long jarg2, cVirtualRobotHaptiqueDrone jarg2_);
  public final static native boolean cFileMappingRobotHaptiqueDroneClient_WriteVirtualRobotHaptiqueDroneStructToMapFile(long jarg1, cFileMappingRobotHaptiqueDroneClient jarg1_, long jarg2, cVirtualRobotHaptiqueDrone jarg2_);
  public final static native void cFileMappingRobotHaptiqueDroneClient_PrintDebug(long jarg1, cFileMappingRobotHaptiqueDroneClient jarg1_, String jarg2, boolean jarg3);
  public final static native void cFileMappingRobotHaptiqueDroneClient_PrintStruct(long jarg1, cFileMappingRobotHaptiqueDroneClient jarg1_, long jarg2, cVirtualRobotHaptiqueDrone jarg2_);
  public final static native long cFileMappingRobotHaptiqueDroneClient_getVirtualRobotHaptiqueDronePtr(long jarg1, cFileMappingRobotHaptiqueDroneClient jarg1_);
  public final static native boolean cFileMappingRobotHaptiqueDroneClient_getDebugMode(long jarg1, cFileMappingRobotHaptiqueDroneClient jarg1_);
  public final static native boolean cFileMappingRobotHaptiqueDroneClient_getVirtualRobotHaptiqueDroneMutexBlocAccess(long jarg1, cFileMappingRobotHaptiqueDroneClient jarg1_);
  public final static native boolean cFileMappingRobotHaptiqueDroneClient_getVirtualRobotHaptiqueDroneUserPresence(long jarg1, cFileMappingRobotHaptiqueDroneClient jarg1_);
  public final static native int cFileMappingRobotHaptiqueDroneClient_getVirtualRobotHaptiqueDroneAxeX(long jarg1, cFileMappingRobotHaptiqueDroneClient jarg1_);
  public final static native int cFileMappingRobotHaptiqueDroneClient_getVirtualRobotHaptiqueDroneAxeY(long jarg1, cFileMappingRobotHaptiqueDroneClient jarg1_);
  public final static native int cFileMappingRobotHaptiqueDroneClient_getVirtualRobotHaptiqueDroneAxeZ(long jarg1, cFileMappingRobotHaptiqueDroneClient jarg1_);
  public final static native void cFileMappingRobotHaptiqueDroneClient_setVirtualRobotHaptiqueDronePtr(long jarg1, cFileMappingRobotHaptiqueDroneClient jarg1_, long jarg2, cVirtualRobotHaptiqueDrone jarg2_);
  public final static native void cFileMappingRobotHaptiqueDroneClient_setDebugMode(long jarg1, cFileMappingRobotHaptiqueDroneClient jarg1_, boolean jarg2);
  public final static native void cFileMappingRobotHaptiqueDroneClient_setVirtualRobotHaptiqueDroneMutexBlocAccess(long jarg1, cFileMappingRobotHaptiqueDroneClient jarg1_, boolean jarg2);
}
