/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class JNIVirtualManettesJNI {
  public final static native void cVirtualManettes_MutexBlocAccess_set(long jarg1, cVirtualManettes jarg1_, boolean jarg2);
  public final static native boolean cVirtualManettes_MutexBlocAccess_get(long jarg1, cVirtualManettes jarg1_);
  public final static native void cVirtualManettes_ManettesDataPtr_set(long jarg1, cVirtualManettes jarg1_, long jarg2);
  public final static native long cVirtualManettes_ManettesDataPtr_get(long jarg1, cVirtualManettes jarg1_);
  public final static native void cVirtualManettes_AxeX_Gauche_set(long jarg1, cVirtualManettes jarg1_, double jarg2);
  public final static native double cVirtualManettes_AxeX_Gauche_get(long jarg1, cVirtualManettes jarg1_);
  public final static native void cVirtualManettes_AxeY_Gauche_set(long jarg1, cVirtualManettes jarg1_, double jarg2);
  public final static native double cVirtualManettes_AxeY_Gauche_get(long jarg1, cVirtualManettes jarg1_);
  public final static native void cVirtualManettes_AxeX_Droite_set(long jarg1, cVirtualManettes jarg1_, double jarg2);
  public final static native double cVirtualManettes_AxeX_Droite_get(long jarg1, cVirtualManettes jarg1_);
  public final static native void cVirtualManettes_AxeY_Droite_set(long jarg1, cVirtualManettes jarg1_, double jarg2);
  public final static native double cVirtualManettes_AxeY_Droite_get(long jarg1, cVirtualManettes jarg1_);
  public final static native long new_cVirtualManettes();
  public final static native void delete_cVirtualManettes(long jarg1);
}
