/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class JNIVirtualTelloEduTelemetryJNI {
  public final static native void cVirtualTelloEduTelemetry_MutexBlocAccess_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, boolean jarg2);
  public final static native boolean cVirtualTelloEduTelemetry_MutexBlocAccess_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_ReadByClient_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, boolean jarg2);
  public final static native boolean cVirtualTelloEduTelemetry_ReadByClient_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_WritebyServer_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, boolean jarg2);
  public final static native boolean cVirtualTelloEduTelemetry_WritebyServer_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_BatteryValue_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_BatteryValue_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_FlyTime_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_FlyTime_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Templ_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_Templ_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Temph_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_Temph_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_ToF_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_ToF_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_H_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_H_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Agx_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, double jarg2);
  public final static native double cVirtualTelloEduTelemetry_Agx_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Agy_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, double jarg2);
  public final static native double cVirtualTelloEduTelemetry_Agy_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Agz_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, double jarg2);
  public final static native double cVirtualTelloEduTelemetry_Agz_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_TelloEduTelemetryDataPtr_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, long jarg2);
  public final static native long cVirtualTelloEduTelemetry_TelloEduTelemetryDataPtr_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Pitch_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_Pitch_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Roll_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_Roll_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Yaw_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, int jarg2);
  public final static native int cVirtualTelloEduTelemetry_Yaw_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Vgx_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, double jarg2);
  public final static native double cVirtualTelloEduTelemetry_Vgx_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Vgy_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, double jarg2);
  public final static native double cVirtualTelloEduTelemetry_Vgy_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Vgz_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, double jarg2);
  public final static native double cVirtualTelloEduTelemetry_Vgz_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native void cVirtualTelloEduTelemetry_Baro_set(long jarg1, cVirtualTelloEduTelemetry jarg1_, double jarg2);
  public final static native double cVirtualTelloEduTelemetry_Baro_get(long jarg1, cVirtualTelloEduTelemetry jarg1_);
  public final static native long new_cVirtualTelloEduTelemetry();
  public final static native void delete_cVirtualTelloEduTelemetry(long jarg1);
}
