/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class JNIVirtualRobotHaptiqueDroneJNI {
  public final static native void cVirtualRobotHaptiqueDrone_MutexBlocAccess_set(long jarg1, cVirtualRobotHaptiqueDrone jarg1_, boolean jarg2);
  public final static native boolean cVirtualRobotHaptiqueDrone_MutexBlocAccess_get(long jarg1, cVirtualRobotHaptiqueDrone jarg1_);
  public final static native void cVirtualRobotHaptiqueDrone_UserPresence_set(long jarg1, cVirtualRobotHaptiqueDrone jarg1_, boolean jarg2);
  public final static native boolean cVirtualRobotHaptiqueDrone_UserPresence_get(long jarg1, cVirtualRobotHaptiqueDrone jarg1_);
  public final static native void cVirtualRobotHaptiqueDrone_RobotHaptiqueDroneDataPtr_set(long jarg1, cVirtualRobotHaptiqueDrone jarg1_, long jarg2);
  public final static native long cVirtualRobotHaptiqueDrone_RobotHaptiqueDroneDataPtr_get(long jarg1, cVirtualRobotHaptiqueDrone jarg1_);
  public final static native void cVirtualRobotHaptiqueDrone_AxeX_set(long jarg1, cVirtualRobotHaptiqueDrone jarg1_, int jarg2);
  public final static native int cVirtualRobotHaptiqueDrone_AxeX_get(long jarg1, cVirtualRobotHaptiqueDrone jarg1_);
  public final static native void cVirtualRobotHaptiqueDrone_AxeY_set(long jarg1, cVirtualRobotHaptiqueDrone jarg1_, int jarg2);
  public final static native int cVirtualRobotHaptiqueDrone_AxeY_get(long jarg1, cVirtualRobotHaptiqueDrone jarg1_);
  public final static native void cVirtualRobotHaptiqueDrone_AxeZ_set(long jarg1, cVirtualRobotHaptiqueDrone jarg1_, int jarg2);
  public final static native int cVirtualRobotHaptiqueDrone_AxeZ_get(long jarg1, cVirtualRobotHaptiqueDrone jarg1_);
  public final static native long new_cVirtualRobotHaptiqueDrone();
  public final static native void delete_cVirtualRobotHaptiqueDrone(long jarg1);
}
